apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  labels:
    group: {{ .Values.ui.group }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: {{ .Values.ui.name }}
  ports:
    - port: {{ .Values.ui.service.port }}       
      targetPort: {{ .Values.ui.container.port }} 
