name: build-and-test

on:
  - push
  - pull_request
  - release

defaults:
  run:
    working-directory: ui

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  integrationtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    env:
      PORT: 3000
      CKAN_URL: https://manage.dev.nhs.marvell-consulting.com/api/3/action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start &
      - run: npm run test:integration

  notify:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - test
      - integrationtest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: github-bot
          SLACK_CHANNEL: developers
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Build failed
