name: deploy-test

on:
  release:
    types:
      - published

jobs:

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo deployprod
