name: deploy-dev

on:
  workflow_run:
    branches:
      - master
    workflows:
      - build-and-test
    types:
      - completed
    conclusion:
      - success

jobs:

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          load: true
      - run: echo deploydev