name: deploy-prod

on:
  release:
    types:
      - published

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo deployprod
