name: UI CI

on:
  [ push, pull_request ]

defaults:
  run:
    working-directory: ui

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: node@${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
